const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")
const { MATERIAL_CODES } = require("../config/materials")

const root = path.resolve(__dirname, "..", "..")
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8")
const pickAll = (source, regex, map) => Array.from(source.matchAll(regex)).map(map)
const uniq = (arr) => Array.from(new Set(arr))

test("材料配置源至少包含一个材料code", () => {
  assert.ok(Array.isArray(MATERIAL_CODES))
  assert.ok(MATERIAL_CODES.length > 0)
  MATERIAL_CODES.forEach(code => assert.equal(typeof code, "string"))
})

test("后端暴露materials接口供前端动态渲染", () => {
  const routes = read("server/routes/catalog.js")
  const controller = read("server/controllers/catalogController.js")
  assert.match(routes, /router\.get\("\/materials",catalogController\.getMaterials\)/)
  assert.match(controller, /const getMaterials=async\(req,res\)=>/)
  assert.match(controller, /res\.json\(MATERIAL_OPTIONS\.map/)
})

test("前端Profile页与Config Prototype页使用materials接口动态渲染", () => {
  const adminJs = read("client/public/js/admin.js")
  const protoJs = read("client/public/js/admin-config-prototype.js")
  assert.match(adminJs, /window\.apiFetch\("\/materials"\)/)
  assert.match(protoJs, /apiFetch\("\/materials"/)
  assert.match(adminJs, /materialWrap\.innerHTML=""/)
  assert.match(protoJs, /materialWrap\.innerHTML=""/)
})

test("configurator使用materials接口动态渲染产品按钮", () => {
  const configuratorJs = read("client/public/js/configurator.js")
  assert.match(configuratorJs, /fetchWithRetry\("\/materials"\)/)
  assert.match(configuratorJs, /const renderProductButtons =/)
  assert.match(configuratorJs, /data-segmented="product"/)
})

test("前端默认材料回退值必须存在于约定列表", () => {
  const adminJs = read("client/public/js/admin.js")
  const protoJs = read("client/public/js/admin-config-prototype.js")
  const fallback1 = pickAll(adminJs, /\|\|"([^"]+)"/g, m => m[1]).filter(v => MATERIAL_CODES.includes(v))
  const fallback2 = pickAll(protoJs, /\|\|"([^"]+)"/g, m => m[1]).filter(v => MATERIAL_CODES.includes(v))
  assert.ok(fallback1.length > 0)
  assert.ok(fallback2.length > 0)
  uniq(fallback1.concat(fallback2)).forEach(v => assert.ok(MATERIAL_CODES.includes(v)))
})

test("后端profile链路仍使用material参数与字段", () => {
  const adminController = read("server/controllers/adminController.js")
  const catalogController = read("server/controllers/catalogController.js")
  const adminService = read("server/services/adminService.js")
  const schemas = read("server/dto/schemas.js")
  assert.match(adminController, /const \{material,category\}=req\.query/)
  assert.match(catalogController, /const \{material,category\}=req\.query/)
  assert.match(adminService, /material:body\.material\|\|""/)
  assert.match(schemas, /material:z\.string\(\)\.optional\(\)\.default\(""\)/)
})

test("profile支持KD Code与Customer Code持久化字段", () => {
  const models = read("server/models.js")
  const db = read("server/db.js")
  const schemas = read("server/dto/schemas.js")
  const adminService = read("server/services/adminService.js")
  const adminJs = read("client/public/js/admin.js")
  assert.match(models, /kdCode:\{type:DataTypes\.STRING\(255\)\}/)
  assert.match(models, /customerCode:\{type:DataTypes\.STRING\(255\)\}/)
  assert.match(db, /ensureColumn\("profiles","kdCode"/)
  assert.match(db, /ensureColumn\("profiles","customerCode"/)
  assert.match(schemas, /kdCode:z\.string\(\)\.optional\(\)\.default\(""\)/)
  assert.match(schemas, /customerCode:z\.string\(\)\.optional\(\)\.default\(""\)/)
  assert.match(adminService, /kdCode:body\.kdCode\|\|""/)
  assert.match(adminService, /customerCode:body\.customerCode\|\|""/)
  assert.match(adminJs, /name:"kdCode"/)
  assert.match(adminJs, /name:"customerCode"/)
})

test("颜色配置支持按product维度保存并驱动前端过滤", () => {
  const models = read("server/models.js")
  const schemas = read("server/dto/schemas.js")
  const adminService = read("server/services/adminService.js")
  const adminProtoJs = read("client/public/js/admin-config-prototype.js")
  const adminProtoHtml = read("client/public/admin-config-prototype.html")
  const configuratorJs = read("client/public/js/configurator.js")
  assert.match(models, /colorMapJson:\{type:DataTypes\.STRING\(4000\)\}/)
  assert.match(schemas, /colorMap:z\.any\(\)\.optional\(\)/)
  assert.match(adminService, /colorMapJson:JSON\.stringify\(map\)/)
  assert.match(adminService, /if\(Array\.isArray\(raw\)\)/)
  assert.match(adminProtoHtml, /data-color-product-select/)
  assert.match(adminProtoJs, /state\.colorMap=/)
  assert.match(adminProtoJs, /readCurrentOptionEditor/)
  assert.match(adminProtoJs, /data-tilt-options/)
  assert.match(adminProtoHtml, /data-louver-opening-config/)
  assert.match(adminProtoHtml, /data-value="None"/)
  assert.match(adminProtoJs, /normalizeLouverOpeningConfig/)
  assert.match(adminProtoJs, /const LOUVER_OPENING_CONFIG_OPTIONS=\["None","1way","2way","Both"\]/)
  assert.match(adminProtoJs, /if\(raw==="none"\)return "None"/)
  assert.match(adminProtoJs, /louverOpening:getLouverOpeningConfigValue\(\)/)
  assert.match(adminService, /const normalizeLouverOpening=\(value\)=>/)
  assert.match(adminService, /if\(raw==="none"\)return "None"/)
  assert.match(adminService, /louverOpening:normalizeLouverOpening\(source\.louverOpening\)/)
  assert.match(configuratorJs, /row && row\.colorMapJson \? JSON\.parse\(row\.colorMapJson\)/)
  assert.match(configuratorJs, /hinge: \(productPair\.hinge && productPair\.hinge\.length \? productPair\.hinge : normalizedMap\.default\.hinge\)/)
  assert.match(configuratorJs, /tilt: \(productPair\.tilt && productPair\.tilt\.length \? productPair\.tilt/)
  assert.match(configuratorJs, /currentLouverOpeningMode = normalizeLouverOpeningMode/)
  assert.match(configuratorJs, /if \(raw === "none"\) return "None"/)
  assert.match(configuratorJs, /if \(normalized === "None"\) return \[\]/)
  assert.match(configuratorJs, /if \(currentLouverOpeningMode === "None"\) \{\s*row\.style\.display = "none"/)
  assert.match(configuratorJs, /louvresOpening: currentLouverOpeningMode === "None" \? "1way"/)
  assert.match(configuratorJs, /applyLouverOpeningRule\(\)/)
})

test("company config保留tiltOptionList字段但业务逻辑不再读写", () => {
  const models = read("server/models.js")
  const schemas = read("server/dto/schemas.js")
  const service = read("server/services/companyConfigService.js")
  const adminProtoHtml = read("client/public/admin-config-prototype.html")
  const adminProtoJs = read("client/public/js/admin-config-prototype.js")
  const configuratorJs = read("client/public/js/configurator.js")
  assert.match(models, /tiltOptionList:\{type:DataTypes\.STRING\(1000\)\}/)
  assert.match(schemas, /tiltOptionList:z\.array\(z\.string\(\)\)\.optional\(\)\.default\(\[\]\)/)
  assert.match(service, /tiltOptionList:\[\]/)
  assert.doesNotMatch(service, /tiltOptionList:parseList\(row\.tiltOptionList\)/)
  assert.doesNotMatch(service, /tiltOptionList:serializeList\(body\.tiltOptionList\)/)
  assert.match(adminProtoHtml, /data-tilt-options/)
  assert.doesNotMatch(adminProtoJs, /tiltOptionList:/)
  assert.match(configuratorJs, /const fallbackTilts = normalizedMap\.default\.tilt && normalizedMap\.default\.tilt\.length/)
})

test("Frame支持按Mount做公司配置二次过滤", () => {
  const models = read("server/models.js")
  const db = read("server/db.js")
  const schemas = read("server/dto/schemas.js")
  const service = read("server/services/companyConfigService.js")
  const html = read("client/public/configurator.html")
  const adminProtoJs = read("client/public/js/admin-config-prototype.js")
  const configuratorJs = read("client/public/js/configurator.js")
  assert.match(models, /profileMountMap:\{type:DataTypes\.STRING\(2000\)\}/)
  assert.match(models, /profileAreaMountMap:\{type:DataTypes\.STRING\(2000\)\}/)
  assert.match(db, /ensureColumn\("company_configs","profileMountMap"/)
  assert.match(db, /ensureColumn\("company_configs","profileAreaMountMap"/)
  assert.match(schemas, /profileMountMap:z\.record\(z\.array\(z\.string\(\)\)\)\.optional\(\)\.default\(\{\}\)/)
  assert.match(schemas, /profileAreaMountMap:z\.record\(z\.array\(z\.string\(\)\)\)\.optional\(\)\.default\(\{\}\)/)
  assert.match(service, /profileMountMap:parseMountMap\(row\.profileMountMap\)/)
  assert.match(service, /profileAreaMountMap:parseMountMap\(row\.profileAreaMountMap\)/)
  assert.match(service, /profileMountMap:serializeMountMap\(body\.profileMountMap\)/)
  assert.match(service, /profileAreaMountMap:serializeMountMap\(body\.profileAreaMountMap\)/)
  assert.match(service, /AVAILABLE_MOUNTS=\["IM","OM","N\.W\.F"\]/)
  assert.match(adminProtoJs, /profileMountMap:\{\}/)
  assert.match(adminProtoJs, /profileAreaMountMap:\{\}/)
  assert.match(adminProtoJs, /data-mount="IM"/)
  assert.match(adminProtoJs, /data-mount="OM"/)
  assert.match(adminProtoJs, /data-mount="N\.W\.F"/)
  assert.match(adminProtoJs, /data-area-mount="IM"/)
  assert.match(adminProtoJs, /profileAreaMountMap:state\.profileAreaMountMap\|\|\{\}/)
  assert.match(configuratorJs, /const profileMountMap = companyConfig\.profileMountMap/)
  assert.match(configuratorJs, /if \(category !== "Frame" \|\| !selectedMount\) return filteredByCompany/)
  assert.match(configuratorJs, /AVAILABLE_MOUNTS = \["IM", "OM", "N\.W\.F"\]/)
  assert.match(configuratorJs, /const shouldApplyFullAreaByConfig = \(\) =>/)
  assert.match(configuratorJs, /profileAreaMountMap: \{\}/)
  assert.doesNotMatch(configuratorJs, /isUsaCompany/)
  assert.match(html, /<option>N\.W\.F<\/option>/)
})

test("TPost在配置器与购物车订单链路中与Stile同级持久化", () => {
  const html = read("client/public/configurator.html")
  const adminJs = read("client/public/js/admin.js")
  const configuratorJs = read("client/public/js/configurator.js")
  const cartJs = read("client/public/js/cart.js")
  const orderCommonJs = read("client/public/js/orders-common.js")
  const schemas = read("server/dto/schemas.js")
  const models = read("server/models.js")
  const db = read("server/db.js")
  const cartService = read("server/services/cartService.js")
  const ordersService = read("server/services/ordersService.js")
  const utils = read("server/utils.js")
  assert.match(html, /Stile&TPost/)
  assert.match(html, /data-tpost-block/)
  assert.match(adminJs, /fields:\["louvresSize","louvresOpening","stile","tpost"\]/)
  assert.match(html, /data-profile-list="TPost"/)
  assert.match(configuratorJs, /selection = \{ louvresSize: "", stile: "", tpost: "", frameType: "" \}/)
  assert.match(configuratorJs, /categories = \["Louver", "Stile", "TPost", "Frame"\]/)
  assert.match(configuratorJs, /keyMap = \{ Louver: "louvresSize", Stile: "stile", TPost: "tpost", Frame: "frameType" \}/)
  assert.match(configuratorJs, /const shouldShowTPost = \(\) => \/T\/i\.test/)
  assert.match(configuratorJs, /\{key:"TPost",label:"TPost"\}/)
  assert.match(cartJs, /TPOST TYPE/)
  assert.match(orderCommonJs, /TPOST TYPE/)
  assert.match(schemas, /tpost:z\.string\(\)\.optional\(\)\.default\(""\)/)
  assert.match(models, /tpost:\{type:DataTypes\.STRING\(64\)\}/)
  assert.match(db, /ensureColumn\("order_lines","tpost"/)
  assert.match(db, /ensureColumn\("cart_lines","tpost"/)
  assert.match(cartService, /tpost:source\.tpost\|\|source\.tPost\|\|""/)
  assert.match(ordersService, /tpost:source\.tpost\|\|source\.tPost\|\|""/)
  assert.match(utils, /tpost:line\.tpost\|\|line\.tPost\|\|""/)
})

test("Admin编辑用户支持可选密码更新", () => {
  const adminJs = read("client/public/js/admin.js")
  const schemas = read("server/dto/schemas.js")
  const service = read("server/services/adminService.js")
  assert.match(adminJs, /\{name:"password",label:adminT\("admin\.user\.col\.password","Password"\),type:"password"\}/)
  assert.match(schemas, /password:z\.string\(\)\.optional\(\)\.default\(""\)/)
  assert.match(service, /if\(body\.password&&String\(body\.password\)\.trim\(\)\)/)
  assert.match(service, /data\.passwordHash=await bcrypt\.hash\(String\(body\.password\),10\)/)
})

test("Order Detail的Add Shutter弹窗打开时清空上次草稿", () => {
  const configuratorJs = read("client/public/js/configurator.js")
  assert.match(configuratorJs, /if \(meta\.mode === "add"\) \{/)
  assert.match(configuratorJs, /localStorage\.removeItem\(draftKey\)/)
  assert.match(configuratorJs, /clearAfterAdd\(\)/)
  assert.match(configuratorJs, /const clearAfterAdd = \(\) => \{[\s\S]*?updatePreview\(\)/)
})

test("订单层新增PO与Side Mark并贯穿购物车列表与导出配置", () => {
  const models = read("server/models.js")
  const db = read("server/db.js")
  const schemas = read("server/dto/schemas.js")
  const cartController = read("server/controllers/cartController.js")
  const cartService = read("server/services/cartService.js")
  const cartHtml = read("client/public/cart.html")
  const cartJs = read("client/public/js/cart.js")
  const ordersCommonJs = read("client/public/js/orders-common.js")
  const adminOrderListHtml = read("client/public/admin-order-list.html")
  const orderHistoryHtml = read("client/public/order-history.html")
  const adminJs = read("client/public/js/admin.js")
  assert.match(models, /po:\{type:DataTypes\.STRING\(50\)\}/)
  assert.match(models, /sideMark:\{type:DataTypes\.STRING\(50\)\}/)
  assert.match(db, /ensureColumn\("orders","po",\{type:Sequelize\.STRING\(50\),allowNull:true\}\)/)
  assert.match(db, /ensureColumn\("orders","sideMark",\{type:Sequelize\.STRING\(50\),allowNull:true\}\)/)
  assert.match(schemas, /const orderMetaSchema=z\.object\(\{/)
  assert.match(schemas, /po:z\.string\(\)\.max\(50\)\.optional\(\)\.default\(""\)/)
  assert.match(schemas, /sideMark:z\.string\(\)\.max\(50\)\.optional\(\)\.default\(""\)/)
  assert.match(cartController, /missing_required_order_meta/)
  assert.match(cartService, /const po=String\(orderMeta&&orderMeta\.po\|\|""\)\.trim\(\)/)
  assert.match(cartService, /const sideMark=String\(orderMeta&&orderMeta\.sideMark\|\|""\)\.trim\(\)/)
  assert.match(cartHtml, /data-order-po/)
  assert.match(cartHtml, /data-order-side-mark/)
  assert.match(cartHtml, /data-order-po maxlength="50"/)
  assert.match(cartHtml, /data-order-side-mark maxlength="50"/)
  assert.match(cartJs, /Please fill PO and Side Mark\./)
  assert.match(cartJs, /PO and Side Mark must be within 50 characters\./)
  assert.match(ordersCommonJs, /<span class="cell-ellipsis" title="\$\{escapeAttr\(poText\)\}">\$\{poText\}<\/span>/)
  assert.match(ordersCommonJs, /<span class="cell-ellipsis" title="\$\{escapeAttr\(sideMarkText\)\}">\$\{sideMarkText\}<\/span>/)
  assert.match(ordersCommonJs, /<div>PO<strong class="order-meta-multiline">\$\{order\.po \|\| ""\}<\/strong><\/div>/)
  assert.match(ordersCommonJs, /<div>Side Mark<strong class="order-meta-multiline">\$\{order\.sideMark \|\| ""\}<\/strong><\/div>/)
  assert.match(adminOrderListHtml, /<th>PO<\/th>/)
  assert.match(orderHistoryHtml, /<th>Side Mark<\/th>/)
  assert.match(adminOrderListHtml, /<table class="table order-table">/)
  assert.match(orderHistoryHtml, /<table class="table order-table">/)
  assert.match(adminJs, /"orderReference","po","sideMark","sqmTotal"/)
})
