const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = path.resolve(__dirname, "..", "..")
const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8")

test("订单详情打印样式使用横向纸张并重排 detail grid", () => {
  const css = read("client/public/css/orders.css")
  const adminCss = read("client/public/css/admin.css")
  const userHtml = read("client/public/order-detail.html")
  assert.match(css, /@page\{size:A4 landscape;margin:8mm\}/)
  assert.match(adminCss, /\.content\{flex:1;min-width:0;padding:28px 32px\}/)
  assert.match(css, /\.order-section-title\{margin:0 0 12px;padding-bottom:12px;border-bottom:1px solid #f1f3f6\}/)
  assert.match(userHtml, /<h4 class="order-section-title">Order Information<\/h4>/)
  assert.match(css, /\.order-detail-panel\{margin-top:16px;min-width:0\}/)
  assert.match(css, /body\[data-page="order-detail"\],body\[data-page="admin-order-detail"\]\{background:#fff\}/)
  assert.match(css, /body\[data-page="admin-order-detail"\] \.sidebar\{display:none!important\}/)
  assert.match(css, /body\[data-page="order-detail"\] \.detail-grid,body\[data-page="admin-order-detail"\] \.detail-grid\{display:grid;grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/)
  assert.match(css, /body\[data-page="order-detail"\] \.detail-col,body\[data-page="admin-order-detail"\] \.detail-col\{display:block;height:auto;width:auto/)
})

test("管理员订单详情页暴露单位切换和打印入口", () => {
  const html = read("client/public/admin-order-detail.html")
  const listHtml = read("client/public/admin-order-list.html")
  const units = read("client/public/js/units.js")
  const ordersJs = read("client/public/js/orders.js")

  assert.match(html, /<body[^>]*class="admin-layout"[^>]*data-page="admin-order-detail"[^>]*data-allow-unit-toggle="1"/)
  assert.match(html, /<aside class="sidebar">/)
  assert.match(html, /data-unit-toggle/)
  assert.match(html, /data-order-print/)
  assert.match(html, /<h4 class="order-section-title" data-i18n="admin\.order_list\.order_info">Order Information<\/h4>/)
  assert.match(html, /<div class="right-actions">[\s\S]*data-unit-toggle[\s\S]*data-order-print[\s\S]*data-order-export[\s\S]*<\/div>/)
  assert.doesNotMatch(html, /data-order-no/)
  assert.doesNotMatch(html, /data-order-date/)
  assert.match(html, /href="\/admin-order-list\.html"/)
  assert.doesNotMatch(listHtml, /data-unit-toggle/)
  assert.doesNotMatch(listHtml, /data-order-print/)
  assert.doesNotMatch(listHtml, /<script src="\/js\/units\.js"><\/script>/)
  assert.match(html, /<script src="\/js\/units\.js"><\/script>/)
  assert.match(units, /const allowAdminToggle = !!\(body && body\.hasAttribute\("data-allow-unit-toggle"\)\)/)
  assert.match(ordersJs, /if \(page === "admin-order-list"\)/)
  assert.match(ordersJs, /window\.renderOrders\(pageRows, tbody, "\/admin-order-detail\.html", \{ showMark: true \}\)/)
  assert.match(ordersJs, /if \(page === "admin-order-detail"\)/)
  assert.match(ordersJs, /const printBtn = window\.qs\("\[data-order-print\]"\)/)
  assert.match(ordersJs, /document\.addEventListener\("unit-change", \(\) => \{/)
})
